name: Code Review GPT

on:
  pull_request:
    branches: [main]

permissions:
  pull-requests: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install code-review-gpt
        run: npm install code-review-gpt

      - name: Run code review script
        run: npx code-review-gpt review --ci=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_SHA: ${{ github.sha }}
          OPENAI_API_KEY: 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
